services:
  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "3010:3010"
    networks:
      - internal

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - internal
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/etc:/etc/grafana
      - ./grafana/css:/usr/share/grafana/public/css
    environment:
      - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource

  posix:
    build:
      context: ./data-server
      args:
        SOURCE: posix
    container_name: posix
    ports:
      - "4000:4000"
    networks:
      - internal

  gds:
    build:
      context: ./data-server
      args:
        SOURCE: gds
    container_name: gds
    ports:
      - "4001:4000"
    networks:
      - internal

  aisio:
    build:
      context: ./data-server
      args:
        SOURCE: aisio
    container_name: aisio
    ports:
      - "4002:4000"
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80" # Expose Nginx on port 80
    depends_on:
      - dashboard
      - grafana
      - posix
      - gds
      - aisio
    networks:
      - internal
    # extra_hosts:
    #   - posix:${POSIX_HOST}
    #   - gds:${GDS_HOST}
    #   - aisio:${AISIO_HOST}

networks:
  internal:
    driver: bridge
