services:
  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "3010:3010"
    networks:
      - internal

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - internal
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/etc:/etc/grafana
      - ./grafana/css:/usr/share/grafana/public/css
    environment:
      - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource

  data:
    build:
      context: ./data-server
    container_name: data
    ports:
      - "4000:4000"
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80" # Expose Nginx on port 80
    depends_on:
      - dashboard
      - grafana
      - data
    networks:
      - internal

networks:
  internal:
    driver: bridge
